### PR TITLE
Fixed a memory allocation bug

### PR DESCRIPTION
**Pull request by zlateski**
Allocating the correct number of bytes (not integers)

### CODE REVIEW

**Comment by kawakami-k** [comment]
Sorry for late reply. I'll check your patch and merge it next week. Thank you.

**Comment by kawakami-k** [comment]
growMemory() eventually calls 
https://github.com/fujitsu/xbyak_aarch64/blob/fjmaster/xbyak_aarch64/xbyak_aarch64_code_array.h#L30
, so the memory size is multiplied by 4. 

Please try following code.
` g++ -std=c++11 -g auto_grow.cpp -DXBYAK_USE_MMAP_ALLOCATOR && ./a.out`

```
#include "../xbyak_aarch64/xbyak_aarch64.h"
using namespace Xbyak_aarch64;
class Generator : public CodeGeneratorAArch64 {
public:
  Generator() : Xbyak_aarch64::CodeGeneratorAArch64(Xbyak_aarch64::DEFAULT_MAX_CODE_SIZE, Xbyak_aarch64::AutoGrow) {};
  void genAddFunc() {
        for(int i=0; i<5000; i++) {
          add(w0, w1, w0);
        }

        ret();
    }

  const uint32_t *gen() {
    genAddFunc();
    ready();
    return getCode();
  }
};

int main() {
  Generator code;

  std::cout << code.getSize() << std::endl;
  int (*f)(int a, int b) = (int (*)(int a, int b))code.gen();
  std::cout << code.getSize() << std::endl;
  std::cout << f(3,1) << std::endl;
  return 0;
}
```

**Comment by herumi** [comment]
The current `alloca(size)` allocates `size * 4` bytes. I think that behavior is very confusing.
How about https://github.com/fujitsu/xbyak_aarch64/pull/24/

**Comment by zlateski** [comment]
I see.

I'd argue that it is a bad design :) I'm using a more sophisticated custom allocator which which assumes that alloc requests bytes.

**Pull request closed without merging**
