### PR TITLE
always use static library

### PR DESCRIPTION
**Pull request by herumi**
This patch removes a header-only mode and xbyak_aarch64 always requires `libxbyak_aarch64.a`.

### CODE REVIEW

**Comment by docularxu** [comment]
Hi, @herumi Would you put an explanation in Readme.md about why header-only mode has to be removed? I don't know. But I suppose there will be people like me who has been interested in this feature ever since you originally developed xbyak for x86.

**Comment by herumi** [comment]
The compile-time with xbyak_aarch64 is more heavy than the original xbyak, so we need a library mode.
I tested some patterns, and I found that it increases compile-time even more using header-only mode if we support both header-only mode and library mode. So I removed the feature.
Do you strongly desire header-only mode?

**Comment by docularxu** [comment]
Thanks @herumi for your reply. No, I don't have a strong reason to keep header-only mode. :)
At this moment, I'm just interested to know the why, which you already answered above.

**Comment by herumi** [comment]
An example of clang -Ofast with add.cpp.

H ; header only
L ; lib

X ; support only H
Y ; support both H and L

compile-time of X ; 6.28 sec
compile-time of Y ; H 4.54 sec, L 10.90 sec

**Pull request merged**
